[package]
name = "wasm-threadify"
version = "0.1.0"
authors = ["Michael Staab <afkoffee@protonmail.com>"]
license = "MIT or Apache-2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
log = "0.4.27"
walrus = "0.23.3"
